# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Qt_Crack_Detection
DESTDIR = ../x64/Debug
QT += core gui widgets
CONFIG += debug
DEFINES += _UNICODE WIN64 QT_DLL QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/$(ConfigurationName)
	C:\opencv249\build\vc15\install\include\opencv\
	C:\opencv249\build\vc15\install\include\opencv2\
	C:\opencv249\build\vc15\install\include\
LIBS += -LC:\opencv249\build\vc15\install\lib\
		-llibopencv_core249                           \  
        -llibopencv_highgui249                        \  
        -llibopencv_imgproc249                        \  
        -llibopencv_ml249                             \  
        -llibopencv_video249                          \  
        -llibopencv_features2d249                     \  
        -llibopencv_calib3d249                        \  
        -llibopencv_objdetect249                      \  
        -llibopencv_contrib249                        \  
        -llibopencv_legacy249                         \  
        -llibopencv_flann249                          \  
        -llibopencv_gpu249                            \  
        -llibopencv_nonfree249                        \  
        -llibopencv_ocl249                            \  
        -llibopencv_photo249                          \  
        -llibopencv_stitching249                      \  
        -llibopencv_superres249                       \  
        -llibopencv_ts249                             \  
        -llibopencv_videostab249  
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
